### ISSUE TITLE
Deploying my complex rails app does not work

### ISSUE THREAD

**Issue by nathansamson** [deis/builder#123]
Context: Real Rails app that works perfectly under deis v1.12 (and before)

Problem 1: Environment variables (which my app relies upon) are not available during the build resulting in this
~~~
ArgumentError: Missing required arguments: aws_access_key_id, aws_secret_access_key
       /tmp/build/vendor/bundle/ruby/2.3.0/gems/fog-core-1.35.0/lib/fog/core/service.rb:244:in `validate_options'
       /tmp/build/vendor/bundle/ruby/2.3.0/gems/fog-core-1.35.0/lib/fog/core/service.rb:268:in `handle_settings'
       /tmp/build/vendor/bundle/ruby/2.3.0/gems/fog-core-1.35.0/lib/fog/core/service.rb:98:in `new'
       /tmp/build/vendor/bundle/ruby/2.3.0/gems/fog-core-1.35.0/lib/fog/core/services_mixin.rb:16:in `new'
       /tmp/build/vendor/bundle/ruby/2.3.0/gems/fog-core-1.35.0/lib/fog/storage.rb:27:in `new'
       /tmp/build/vendor/bundle/ruby/2.3.0/gems/carrierwave-0.10.0/lib/carrierwave/uploader/configuration.rb:83:in `eager_load_fog'
       /tmp/build/vendor/bundle/ruby/2.3.0/gems/carrierwave-0.10.0/lib/carrierwave/uploader/configuration.rb:96:in `fog_credentials='
       /tmp/build/config/initializers/carrierwave.rb:8:in `block in <top (required)>'
       /tmp/build/vendor/bundle/ruby/2.3.0/gems/carrierwave-0.10.0/lib/carrierwave/uploader/configuration.rb:118:in `configure'
       /tmp/build/vendor/bundle/ruby/2.3.0/gems/carrierwave-0.10.0/lib/carrierwave.rb:14:in `configure'
       /tmp/build/config/initializers/carrierwave.rb:7:in `<top (required)>'
       /tmp/build/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
       /tmp/build/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `block in load'
       /tmp/build/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
       /tmp/build/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
       /tmp/build/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5/lib/rails/engine.rb:652:in `block in load_config_initializer'
       /tmp/build/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5/lib/active_support/notifications.rb:166:in `instrument'
       /tmp/build/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5/lib/rails/engine.rb:651:in `load_config_initializer'
       /tmp/build/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
       /tmp/build/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5/lib/rails/engine.rb:615:in `each'
       /tmp/build/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5/lib/rails/engine.rb:615:in `block in <class:Engine>'
       /tmp/build/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `instance_exec'
       /tmp/build/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `run'
       /tmp/build/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5/lib/rails/initializable.rb:55:in `block in run_initializers'
       /tmp/build/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5/lib/rails/initializable.rb:44:in `each'
       /tmp/build/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5/lib/rails/initializable.rb:44:in `tsort_each_child'
       /tmp/build/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5/lib/rails/initializable.rb:54:in `run_initializers'
       /tmp/build/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5/lib/rails/application.rb:352:in `initialize!'
       /tmp/build/config/environment.rb:5:in `<top (required)>'
       /tmp/build/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
       /tmp/build/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
       /tmp/build/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
       /tmp/build/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
       /tmp/build/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5/lib/rails/application.rb:328:in `require_environment!'
       /tmp/build/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5/lib/rails/application.rb:457:in `block in run_tasks_blocks'
       /tmp/build/vendor/bundle/ruby/2.3.0/gems/sprockets-rails-3.0.0/lib/sprockets/rails/task.rb:62:in `block (2 levels) in define'
       Tasks: TOP => environment
       (See full trace by running task with --trace)
       !
       !     Precompiling assets failed.

~~~

Problem 2 (resulting from 1)
The git push does not stop but just hangs after this error. The pod describe mentions

~~~
  FirstSeen	LastSeen	Count	From			SubobjectPath				ReasonMessage
  ─────────	────────	─────	────			─────────────				─────────────
  3m		3m		1	{scheduler }							Scheduled	Successfully assigned bplpp-demo-git-f784fa4f to 172.17.8.104
  3m		3m		1	{kubelet 172.17.8.104}	implicitly required container POD	PulledContainer image "gcr.io/google_containers/pause:0.8.0" already present on machine
  3m		3m		1	{kubelet 172.17.8.104}	implicitly required container POD	Created		Created with docker id 49af201f461e
  3m		3m		1	{kubelet 172.17.8.104}	implicitly required container POD	Started		Started with docker id 49af201f461e
  3m		3m		1	{kubelet 172.17.8.104}	spec.containers{deis-slugbuilder}	PulledContainer image "quay.io/deis/slugbuilder:2.0.0-alpha" already present on machine
  3m		3m		1	{kubelet 172.17.8.104}	spec.containers{deis-slugbuilder}	Created		Created with docker id 231273ff568f
  3m		3m		1	{kubelet 172.17.8.104}	spec.containers{deis-slugbuilder}	Started		Started with docker id 231273ff568f
  17s		17s		1	{kubelet 172.17.8.104}	implicitly required container POD	Killing		Killing with docker id 49af201f461e
~~~

**Comment by arschles** [comment]
@nathansamson thanks for this, I'll be looking into it tomorrow. Also, problem 2 is related to #118, and a fix for that is in the works is related to the `git push` not finishing. A fix for that is in the works in #115.

**Comment by arschles** [comment]
@nathansamson I believe we've fixed this as a result of https://github.com/deis/builder/pull/133 ([This line](https://github.com/deis/builder/blob/master/pkg/gitreceive/build.go#L148) specifically, which pushes the config variables into the builder pod manifest). Are you able to try launching a `v2-beta` Deis cluster to confirm?

**Comment by arschles** [comment]
@nathansamson closing this for now. Can you please re-open if you see similar issues in the future? Thanks.
