### ISSUE TITLE
Deploying example-ruby-sinatra fails hard

### ISSUE THREAD

**Issue by krancour** [deis/builder#172]
```
[kent@mbp example-ruby-sinatra]$ git push deis master
Warning: Permanently added '[deis.micro-kube.io]:2222,[172.17.8.100]:2222' (RSA) to the list of known hosts.
Counting objects: 126, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (71/71), done.
Writing objects: 100% (126/126), 26.52 KiB | 0 bytes/s, done.
Total 126 (delta 52), reused 107 (delta 47)
Running in debug mode
Running git hook
read [0000000000000000000000000000000000000000,dd5c83b9dbf6f06f52e95a70757aea35a925144c,refs/heads/master]
Workflow request /v2/hooks/push (body elided)
Workflow request POST /v2/hooks/config
{"receive_user":"kent","receive_repo":"famous-whitecap"}
got the following config back for app famous-whitecap: {Owner:kent App:famous-whitecap Values:map[] Memory:map[] CPU:map[] Tags:map[] UUID:6018f8ff-1d56-4856-a44b-d7221827fb70 Created:2016-02-11 21:19:19 +0000 UTC Updated:2016-02-11 21:19:19 +0000 UTC}
running [git archive --format=tar.gz --output=famous-whitecap.tar.gz dd5c83b9] in directory /home/git/famous-whitecap.git
running [tar -xzf famous-whitecap.tar.gz -C /home/git/famous-whitecap.git/build/tmp782481307/] in directory /home/git/famous-whitecap.git
create bucket error: BucketAlreadyExists: The requested bucket name is not available.
remote: status code: 409, request id: A3AXZ3561ZESROQ0
Uploading tar to http://10.3.0.103:9000/git/home/famous-whitecap:git-dd5c83b9/tar
Starting build... but first, coffee!
Starting pod slugbuild-famous-whitecap-dd5c83b9-b8731f17
Pod spec: {
  "metadata": {
    "name": "slugbuild-famous-whitecap-dd5c83b9-b8731f17",
    "namespace": "deis",
    "creationTimestamp": null,
    "labels": {
      "heritage": "deis",
      "version": "2.0.0-beta"
    }
  },
  "spec": {
    "volumes": [
      {
        "name": "minio-user",
        "secret": {
          "secretName": "minio-user"
        }
      }
    ],
    "containers": [
      {
        "name": "deis-slugbuilder",
        "image": "quay.io/deisci/slugbuilder:v2-beta",
        "env": [
          {
            "name": "DEBUG",
            "value": "1"
          },
          {
            "name": "TAR_URL",
            "value": "http://10.3.0.103:9000/git/home/famous-whitecap:git-dd5c83b9/tar"
          },
          {
            "name": "put_url",
            "value": "http://10.3.0.103:9000/git/home/famous-whitecap:git-dd5c83b9/push"
          }
        ],
        "resources": {},
        "volumeMounts": [
          {
            "name": "minio-user",
            "readOnly": true,
            "mountPath": "/var/run/secrets/object/store"
          }
        ],
        "imagePullPolicy": "Always"
      }
    ],
    "restartPolicy": "Never",
    "serviceAccountName": ""
  },
  "status": {}
}

+ app_dir=/app
+ build_root=/tmp/build
+ cache_root=/tmp/cache
+ buildpack_root=/tmp/buildpacks
+ mkdir -p /app
+ mkdir -p /tmp/cache
+ mkdir -p /tmp/buildpacks
+ mkdir -p /tmp/build/.profile.d
+ MC_PREFIX='mc --quiet -C /app/mc_config'
+ [[ -z http://10.3.0.103:9000/git/home/famous-whitecap:git-dd5c83b9/tar ]]
+ [[ -e /var/run/secrets/object/store/access-key-id ]]
+ [[ -e /var/run/secrets/object/store/access-secret-key ]]
++ cat /var/run/secrets/object/store/access-key-id
+ keyID=8TZRY2JRWMPT6UMXR6I5
++ cat /var/run/secrets/object/store/access-secret-key
+ secretKey=gbstrOvotMMcg2sMfGUhA5a6Et/EI5ALtIHsobYk
++ awk -F/ '{print $3}'
++ echo http://10.3.0.103:9000/git/home/famous-whitecap:git-dd5c83b9/tar
+ domain=10.3.0.103:9000
+ mc --quiet -C /app/mc_config config host add http://10.3.0.103:9000 8TZRY2JRWMPT6UMXR6I5 gbstrOvotMMcg2sMfGUhA5a6Et/EI5ALtIHsobYk
+ mc --quiet -C /app/mc_config cp http://10.3.0.103:9000/git/home/famous-whitecap:git-dd5c83b9/tar /tmp/slug.tgz
+ tar -xzf /tmp/slug.tgz -C /app/
+ unset TAR_URL
+ [[ '' == \- ]]
+ slug_file=/tmp/slug.tgz
+ [[ -n '' ]]
+ app_dir=/app
+ build_root=/tmp/build
+ cache_root=/tmp/cache
+ buildpack_root=/tmp/buildpacks
+ mkdir -p /app
+ mkdir -p /tmp/cache
+ mkdir -p /tmp/buildpacks
+ mkdir -p /tmp/build/.profile.d
+ '[' -d /tmp/app ']'
+ cp -r /app/. /tmp/build
+ export APP_DIR=/app
+ APP_DIR=/app
+ export HOME=/app
+ HOME=/app
++ openssl rand -base64 32
+ export REQUEST_ID=jbn+CK/57e1ofgZYFk8yqDJrYIDxhhOb3iT1uyNaELE=
+ REQUEST_ID=jbn+CK/57e1ofgZYFk8yqDJrYIDxhhOb3iT1uyNaELE=
+ export STACK=cedar-14
+ STACK=cedar-14
+ [[ -n '' ]]
+ buildpacks=($buildpack_root/*)
+ selected_buildpack=
+ [[ -n '' ]]
+ for buildpack in '"${buildpacks[@]}"'
++ /tmp/buildpacks/heroku-buildpack-clojure.git/bin/detect /tmp/build
+ buildpack_name=no
+ for buildpack in '"${buildpacks[@]}"'
++ /tmp/buildpacks/heroku-buildpack-go.git/bin/detect /tmp/build
+ buildpack_name=no
+ for buildpack in '"${buildpacks[@]}"'
++ /tmp/buildpacks/heroku-buildpack-gradle.git/bin/detect /tmp/build
+ buildpack_name=no
+ for buildpack in '"${buildpacks[@]}"'
++ /tmp/buildpacks/heroku-buildpack-grails.git/bin/detect /tmp/build
+ buildpack_name=no
+ for buildpack in '"${buildpacks[@]}"'
++ /tmp/buildpacks/heroku-buildpack-java.git/bin/detect /tmp/build
+ buildpack_name=no
+ for buildpack in '"${buildpacks[@]}"'
++ /tmp/buildpacks/heroku-buildpack-multi.git/bin/detect /tmp/build
+ buildpack_name='no .buildpacks file'
+ for buildpack in '"${buildpacks[@]}"'
++ /tmp/buildpacks/heroku-buildpack-nodejs.git/bin/detect /tmp/build
+ buildpack_name=
+ for buildpack in '"${buildpacks[@]}"'
++ /tmp/buildpacks/heroku-buildpack-php.git/bin/detect /tmp/build
+ buildpack_name=
+ for buildpack in '"${buildpacks[@]}"'
++ /tmp/buildpacks/heroku-buildpack-play.git/bin/detect /tmp/build
+ buildpack_name=no
+ for buildpack in '"${buildpacks[@]}"'
++ /tmp/buildpacks/heroku-buildpack-python.git/bin/detect /tmp/build
+ buildpack_name=
+ for buildpack in '"${buildpacks[@]}"'
++ /tmp/buildpacks/heroku-buildpack-ruby.git/bin/detect /tmp/build
+ buildpack_name=Ruby
+ selected_buildpack=/tmp/buildpacks/heroku-buildpack-ruby.git
+ break
+ [[ -n /tmp/buildpacks/heroku-buildpack-ruby.git ]]
+ echo_title 'Ruby app detected'
+ output_redirect
+ [[ /tmp/slug.tgz == \- ]]
+ cat -
----->' Ruby app detected
-----> Ruby app detected
+ ensure_indent
+ read line
+ /tmp/buildpacks/heroku-buildpack-ruby.git/bin/compile /tmp/build /tmp/cache
/tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack/shell_helpers.rb:49:in `run!'+ [[ ! == --* ]]
: Command: 'set -o pipefail; curl --fail --retry 3 --retry-delay 1 --connect-timeout 3 --max-time 30 https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/bundler-1.9.7.tgz -s -o - | tar zxf - ' failed unexpectedly: (LanguagePack::Fetcher::FetchError)

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack/fetcher.rb:24:in `fetch_untar'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack/helpers/bundler_wrapper.rb:118:in `block (2 levels) in fetch_bundler'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack/helpers/bundler_wrapper.rb:117:in `chdir'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack/helpers/bundler_wrapper.rb:117:in `block in fetch_bundler'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack/instrument.rb:17:in `block in instrument'
remote: from /usr/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack/instrument.rb:16:in `instrument'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack/helpers/bundler_wrapper.rb:84:in `instrument'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack/helpers/bundler_wrapper.rb:114:in `fetch_bundler'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack/helpers/bundler_wrapper.rb:33:in `install'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack/ruby.rb:32:in `bundler'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack/rails5.rb:9:in `block in use?'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack/instrument.rb:17:in `block in instrument'
remote: from /usr/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack/instrument.rb:16:in `instrument'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack/base.rb:48:in `instrument'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack/rails5.rb:8:in `use?'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack.rb:17:in `block (2 levels) in detect'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack.rb:16:in `each'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack.rb:16:in `detect'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack.rb:16:in `block in detect'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack/instrument.rb:17:in `block in instrument'
remote: from /usr/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack/instrument.rb:16:in `instrument'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack.rb:13:in `detect'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/bin/compile:12:in `block in <main>'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack/instrument.rb:35:in `call'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack/instrument.rb:35:in `block in trace'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack/instrument.rb:17:in `block in instrument'
remote: from /usr/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack/instrument.rb:16:in `instrument'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack/instrument.rb:35:in `trace'
remote: from /tmp/buildpacks/heroku-buildpack-ruby.git/bin/compile:11:in `<main>'
+ output_redirect
+ [[ /tmp/slug.tgz == \- ]]
+ cat -
      ' '!'
       !
+ read line
+ [[ !     Command: 'set -o pipefail; curl --fail --retry 3 --retry-delay 1 --connect-timeout 3 --max-time 30 https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/bundler-1.9.7.tgz -s -o - | tar zxf - ' failed unexpectedly: == --* ]]
+ output_redirect
+ [[ /tmp/slug.tgz == \- ]]
+ cat -
      ' '!     Command: '\''set -o pipefail; curl --fail --retry 3 --retry-delay 1 --connect-timeout 3 --max-time 30 https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/bundler-1.9.7.tgz -s -o - | tar zxf - '\'' failed unexpectedly:'
       !     Command: 'set -o pipefail; curl --fail --retry 3 --retry-delay 1 --connect-timeout 3 --max-time 30 https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/bundler-1.9.7.tgz -s -o - | tar zxf - ' failed unexpectedly:
+ read line
+ [[ ! == --* ]]
+ output_redirect
+ [[ /tmp/slug.tgz == \- ]]
+ cat -
      ' '!'
       !
+ read line
+ [[ !     gzip: stdin: unexpected end of file == --* ]]
      ' '!     gzip: stdin: unexpected end of file'
+ output_redirect
+ [[ /tmp/slug.tgz == \- ]]
+ cat -
       !     gzip: stdin: unexpected end of file
+ read line
+ [[ !     tar: Child returned status 1 == --* ]]
+ output_redirect
+ [[ /tmp/slug.tgz == \- ]]
+ cat -
      ' '!     tar: Child returned status 1'
       !     tar: Child returned status 1
+ read line
+ [[ !     tar: Error is not recoverable: exiting now == --* ]]
+ output_redirect
+ [[ /tmp/slug.tgz == \- ]]
+ cat -
      ' '!     tar: Error is not recoverable: exiting now'
       !     tar: Error is not recoverable: exiting now
+ read line
+ [[ ! == --* ]]
+ output_redirect
+ [[ /tmp/slug.tgz == \- ]]
+ cat -
      ' '!'
       !
+ read line
size of logs streamed 9847
Build complete.
Launching app.
Launching...
Workflow request POST /v2/hooks/build
{"sha":"dd5c83b9","receive_user":"kent","receive_repo":"famous-whitecap","image":"http://10.3.0.103:9000/git/home/famous-whitecap:git-dd5c83b9/push/slug.tgz","procfile":{"web":"bundle exec ruby web.rb -p ${PORT:-5000}"},"dockerfile":""}

Done, famous-whitecap:v2 deployed to Deis

Use 'deis open' to view this application in your browser

To learn more, use 'deis help' or visit http://deis.io

running [git gc] in directory /home/git/famous-whitecap.git
To ssh://git@deis.micro-kube.io:2222/famous-whitecap.git
 * [new branch]      master -> master
```

**Comment by gabrtv** [comment]
Looks to me like an intermittent network error in `bundler` resulting in a gzip failure:

```
+ /tmp/buildpacks/heroku-buildpack-ruby.git/bin/compile /tmp/build /tmp/cache
/tmp/buildpacks/heroku-buildpack-ruby.git/lib/language_pack/shell_helpers.rb:49:in `run!'+ [[ ! == --* ]]
: Command: 'set -o pipefail; curl --fail --retry 3 --retry-delay 1 --connect-timeout 3 --max-time 30 https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/bundler-1.9.7.tgz -s -o - | tar zxf - ' failed unexpectedly: (LanguagePack::Fetcher::FetchError)

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

In any event, the fact that we didn't fail the `git receive-pack` and exit non-zero is definitely a problem.

**Comment by bacongobbler** [comment]
related to the non-zero error: https://github.com/deis/deis/issues/4695

**Comment by arschles** [comment]
also related: https://github.com/deis/builder/issues/97

**Comment by aledbf** [comment]
@krancour can you test a builder image from master? (I fixed the exit error code [here](https://github.com/deis/builder/pull/166))

**Comment by mboersma** [comment]
I've tested a lot with example-ruby-sinatra and not seen this error. I think it was a network error when it couldn't fetch `bundler`, so not really something Deis could fix.
