### ISSUE TITLE
Internal Server Error when tried to remove few ssh-keys with the same name.

### ISSUE THREAD

**Issue by lzerma** [deis/builder#416]
Hi Guys, 

I'm facing problems when try to remove old keys from a specific user that has many keys with the same name. 

To reproduce probably should be create an user, add few keys into it with the same name for the key (option -C on ssh-keygen command) and then try to remove. You will get an Internal Server Error from the API.

<img width="448" alt="screenshot 2016-08-29 15 53 47" src="https://cloud.githubusercontent.com/assets/1020217/18055714/db2c04ac-6e00-11e6-9dff-5368f7fa83e0.png">

**Comment by Joshua-Anderson** [comment]
Sorry you're having issues!

Could you possibly post the logs from the controller when this happens?

**Comment by lzerma** [comment]
Not sure if the log would help you, but here you go.
```
[2016-08-29T17:02:45+00:00] - deis/deis-controller - 172.20.0.38 - - - 500 - "DELETE /v2/keys/travis_ci HTTP/1.1" - 389 - "-" - "Deis Client vv2.4.0" - "~^deis\x5C.(?<domain>.+)$" - 10.0.81.130:80 - deis.aeaeae.eu - 0.007 - 0.007
```

**Comment by Joshua-Anderson** [comment]
That log line looks like it came from the router, not the controller. To get controller log lines I run: 

```
$ kubectl --namespace=deis get po
NAME                                     READY     STATUS    RESTARTS   AGE
...
deis-controller-3080940544-52mhj         1/1       Running   0          50m
$ kubectl --namespace=deis logs deis-controller-3080940544-52mhj
```

You should see some python stacktrace that was the result of the 500 error.

**Comment by lzerma** [comment]
Hi @Joshua-Anderson, sorry I did get the deis-controller log, but from the Kibana logs rather than the container.
Follow the correct log now: 
```
10.244.2.7 "GET /v2/keys/?limit=100 HTTP/1.1" 200 4349 "Deis Client vv2.4.0"
ERROR:root:Uncaught Exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 471, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/mixins.py", line 86, in destroy
    instance = self.get_object()
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/generics.py", line 97, in get_object
    obj = get_object_or_404(queryset, **filter_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/generics.py", line 20, in get_object_or_404
    return _get_object_or_404(queryset, *filter_args, **filter_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/shortcuts.py", line 155, in get_object_or_404
    return queryset.get(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 391, in get
    (self.model._meta.object_name, num)
api.models.key.MultipleObjectsReturned: get() returned more than one Key -- it returned 7!
10.244.2.7 "DELETE /v2/keys/travis_ci HTTP/1.1" 500 25 "Deis Client vv2.4.0"
```

**Comment by Joshua-Anderson** [comment]
Thanks for the stacktrace!

Since this is an issue with the controller component and not the builder, I moved the issue there so that the right people see it and it can be better tracked. See deis/controller#1023
